# Generated by Django 4.0.3 on 2022-06-23 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingLIst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchased_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name', models.TextField(blank=True, max_length=144, null=True)),
                ('Cost', models.FloatField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=255, null=True)),
                ('Bought_Item', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Shopping Checklist Item',
                'verbose_name_plural': 'Shopping Checklist Items List',
                'db_table': 'shopping_checklist',
            },
        ),
    ]
