# Generated by Django 4.0.3 on 2022-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
